source: src
destination: build

title: "Totally Wanderlost"
description: "Nicole and James travel the world"
instagram: "https://instagram.com/totallywanderlost"
github: "https://github.com/totallywanderlost"
copyright_name: "Nicole Kay & James White"
