title: "Totally Wanderlost"
description: "Nicole and James travel the world"
email: "nicolejkay@gmail.com"
instagram: "https://instagram.com/totallywanderlost"
github: "https://github.com/totallywanderlost"
copyright_name: "Nicole Kay & James White"