name: data

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-python@v3
        with:
          cache: pipenv
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          make setup_pipenv
          make pipenv
      - name: Fetch Data
        run: make fetch trip=5149612 file=src/_data/journey.json
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }}
          CLOUDFLARE_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }}
      - name: Commit Changes
        run: |
          git config user.name "🤖"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/_data/journey.json
          git diff-index --quiet HEAD src/_data/journey.json || git commit -m "Update journey.json"
          git push
