name: data

on:
  workflow_dispatch:
  schedule:
    - cron: "* 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-python@v3
        with:
          cache: pipenv
      - name: Install Dependencies
        run: make setup_pipenv
      - name: Fetch Data
        run: make fetch trip=5032179 file=src/assets/data/journey.json
      - name: Commit Changes
        run: |
          git config user.name "🤖"
          git add src/assets/data/journey.json
          git diff-index --quiet HEAD src/assets/data/journey.json || git commit -m "Update journey.json"
          git push
