name: data

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "* 0 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          cache: pipenv
      - name: Install Dependencies
        run: make setup_pipenv
      - name: Fetch Data
        run: make fetch trip=5032179 file=src/assets/data/journey.json
      - name: Commit Changes
        run: |
          git config user.name "🤖"
          git config user.email "dev.jameswhite@gmail.com"
          git add src/assets/data
          git diff-index --quiet HEAD src/assets/data || git commit -m "Updated src/assets/data"
          git push
      - name: Deploy
        # TODO: only run if we committed changes
        run: gh workflow run website.yml --ref $GITHUB_SHA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
